plugins {
   id 'java'
   id 'application'
   id 'org.ajoberstar.git-publish' version '4.2.0'
   id 'pmd'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.toVersion(21)
    targetCompatibility = JavaVersion.toVersion(21)
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.0'
    testImplementation 'org.hamcrest:hamcrest-library:2.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test) {
    useJUnitPlatform()
    ignoreFailures = true
    testLogging {
        events "passed", "skipped", "failed"
        }
}

pmd {
    ignoreFailures = true
}

application { //Allows  ./gradlew run --args=path-to-test-data
    mainClass = 'edu.odu.cs.MostCommonWords'
}

javadoc {
    destinationDir = file("$buildDir/reports/javadoc")
}

task reports(dependsOn: ['javadoc', 'test', 'pmdMain'])

gitPublish {
    repoUri = 'https://github.com/ODU-CS351-F26/CS351--ciAsst--jmcano22.git'
    branch = 'gh-pages'
    commitMessage = 'Deploy project website'
    contents {
        from 'src/main/html'
        into('reports') {
            from 'build/reports'
        }
    }
}

task deployReports(dependsOn: ['reports', 'gitPublishPush'])